### ISSUE TITLE
Allow complex `when` conditions

### ISSUE THREAD

**Issue by awinograd** [suzuki-shunsuke/circleci-config-merge#321]
https://github.com/suzuki-shunsuke/circleci-config-merge/pull/47 adds support for simple one-line when conditions. However, circleci's configuration supports more ocmplex conditions as described by https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows

**Comment by suzuki-shunsuke** [comment]
Sorry for late reply.
I'm taking a look.
- https://circleci.com/docs/configuration-reference/#logic-statement-examples

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/circleci-config-merge/pull/399

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/suzuki-shunsuke/circleci-config-merge/releases/tag/v1.1.3

Thank you for your report!
